DROP TRIGGER ALUM_C
DELIMITER //

CREATE TRIGGER ALUM_C 
AFTER INSERT ON asignaturas
for each row 
BEGIN
	UPDATE DEPARTAMENTOS as D 
		SET
			NUM_ASIG = (SELECT COUNT(*) FROM asignaturas WHERE COD_DEPAR =NEW.COD_DEPAR )
		WHERE 
			COD_DEPAR =NEW.COD_DEPAR ;
END //

DELIMITER ;