CREATE TABLE AUDIT_EVALUACIONES(
codigo int(11) NOT NULL AUTO_INCREMENT,
usuario varchar(100),
fecha datetime,
COD_EVALUACION INT(4),
NUM_ALUMNO INT(4) REFERENCES ALUMNOS (NUM_ALUMNO),
COD_ASIG INT(4) REFERENCES ASIGNATURAS (COD_ASIG),
NOTA float(3,1),
PRIMARY KEY (`codigo`))
ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 ;

drop TRIGGER auditoriaEvaluaciones2;

delimiter $$
CREATE TRIGGER auditoriaEvaluaciones2
after INSERT ON evaluaciones 
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_EVALUACIONES (usuario, fecha , COD_EVALUACION,NUM_ALUMNO,COD_ASIG,NOTA)
      values (CURRENT_USER(), NOW(),new.COD_EVALUACION,new.NUM_ALUMNO,new.COD_ASIG,new.NOTA);
END$$
delimiter ;

 